version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ubuntu/build
file_exits_behaviour: OVERWRITE
hooks:
  BeforeInstall:
    - location: scripts/docker_clear.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/build.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
