env:
  open-ai:
    key: ${OPEN_AI_API}
    uri: https://api.openai.com/v1/chat/completions
  papago:
    id: ${PAPAGO_ID}
    secret: ${PAPAGO_SECRET}
    uri: https://naveropenapi.apigw.ntruss.com/nmt/v1/translation
  google:
    key: ${GOOGLE_API_KEY}

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          import_files: db_setting.sql
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PW}
  jwt:
    secret: ${JWT_SECRET}

cloud:
  aws:
    s3:
      bucket: heat-back-s3
    stack:
      auto: false
    region:
      auto: false
      static: ap-northeast-2
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
      instance-profile: true

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
        internal:
          InstanceMetadataServiceResourceFetcher: error
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
    root: info